### ISSUE TITLE
Consistent fire problem

### ISSUE THREAD

**Issue by Julienraptor01** [RuffleSteels/Firorize#10]
This is only an issue when using consistent fire.
When standing on the edge on a block, even if hitbox is in blue flame and we take 2 damage points, flame is orange.

![2022-05-27_20 03 27](https://user-images.githubusercontent.com/49841713/170766249-79b4299b-1cd3-492b-ad9e-7a1950f827fc.png)

**Comment by Julienraptor01** [comment]
I guess this is because most of the hitbox is out of the blue flame but this shouldn't be the case.
If any any part of the hitbox is in blue fire then overlay should be blue.

**Comment by RuffleSteels** [comment]
Yes, this is an issue due to where I'm calling the check within the mixin class, I will attempt to fix tomorrow. Thanks!
