### ISSUE TITLE
1.20.4/5

### ISSUE THREAD

**Issue by motyI** [RuffleSteels/Firorize#16]
the mod crashes in 1.20.4, so it would be nice if it was updated to either the current version or when 1.20.5 comes out

**Comment by SirenGlitch** [comment]
Thought I'd update you: Still crashes in 1.20.4 using code from f7267ea, but seeing as the commit was 5 days ago it looks like 1.20.4+ support could be coming very soon

**Comment by RuffleSteels** [comment]
Its a complete overhaul, you can now customize fire into any color depending on the block its on / the biome its in
