### ISSUE TITLE
Make Mod Menu Optional

### ISSUE THREAD

**Issue by VaporeonScripts** [RuffleSteels/Firorize#18]
Yo, i wanted to use Ur mod in a modpack, which is great as ur mod offers many customization and i like the biome color idea, altough i use a different mod menu mod, so using ur requires mod menu mod, which i cant add, may u flag mod menu as optional? (Thank You!)

**Comment by RuffleSteels** [comment]
Yeah i will try add a keybind to open the menu as well then, thanks for the heads up

**Comment by RuffleSteels** [comment]
> Yo, i wanted to use Ur mod in a modpack, which is great as ur mod offers many customization and i like the biome color idea, altough i use a different mod menu mod, so using ur requires mod menu mod, which i cant add, may u flag mod menu as optional? (Thank You!)

What modpack are you going to add it in? Also which mod menu mod are you using?

**Comment by VaporeonScripts** [comment]
hi, in my own modpack, its a fork of the well known "aof 7" but with alot more mods (600 mods total), reguarding the mod menu mod, idrk, im asking rn, if i find out the name i will inform u quickly

**Comment by VaporeonScripts** [comment]
mod menu name is "catalogue"

**Comment by RuffleSteels** [comment]
Fixed with 08bb139
