### ISSUE TITLE
Causes Create Haunting Recipes in REI to display with the wrong color fire

### ISSUE THREAD

**Issue by NolanHewitt** [RuffleSteels/Firorize#19]
Not sure if this is possible to change using the config as it doesn't seem to be place on any real block. Previous versions of this mod before it was called Firorize didn't cause this issue.
Without The Mod or with pre-firorize versions:
![huge_2024-08-17_04 12 16](https://github.com/user-attachments/assets/335f7de8-f671-4038-9b7a-3c3723cd2d7e)
With The Mod:
![huge_2024-08-17_04 15 03](https://github.com/user-attachments/assets/32f351ab-89cf-4b62-9b83-f900550199c0)

**Comment by RuffleSteels** [comment]
hi, what mods do you have installed?

**Comment by RuffleSteels** [comment]
> Not sure if this is possible to change using the config as it doesn't seem to be place on any real block. Previous versions of this mod before it was called Firorize didn't cause this issue. Without The Mod or with pre-firorize versions

I have fixed it to default back to the regular fire/soul fire texture. I could also make it default to whatever you customized to go ontop of soul sand. What would you prefer it to work like?

**Comment by NolanHewitt** [comment]
Hmmm, I guess using whatever is customized for soul sand would be best. That should default to a blue fire by default then right?

**Comment by RuffleSteels** [comment]
Yeah its blue unless you change it, so ill default it to that, the patch should be released sometime today.

**Comment by NolanHewitt** [comment]
That would be perfect, thank you!

**Comment by RuffleSteels** [comment]
fixed with 73d8893009979e22de2a302f98ca681f8a6552fa
