### ISSUE TITLE
Non Power of two texture

### ISSUE THREAD

**Issue by IThundxr** [RuffleSteels/Firorize#22]
https://github.com/RuffleSteels/Firorize/blob/master/src/main/resources/assets/firorize/textures/block/arrow_left.png

Textures should always be square and the size should always be a power of two, UV's can be used to pull the portion of what you need, odd sized textures end up dropping the mipmap level, in this case all the way to 0.

`Texture firorize:block/arrow_left with size 12x7 limits mip level from 3 to 0`

**Comment by RuffleSteels** [comment]
Fixed with 76b9e4b

**Comment by IThundxr** [comment]
The texture should be 16x16 since 12 isn't a power of two

**Comment by RuffleSteels** [comment]
yep ofc my bad

**Comment by RuffleSteels** [comment]
properly fixed now
