### ISSUE TITLE
Players are only on soul fire if you are, even if they aren't, and have a lot of flickering if so

### ISSUE THREAD

**Issue by altrisi** [RuffleSteels/Firorize#3]
Since player entities are processed differently, with multiple players, they'll only be on soul fire if you are, and stop being on soul fire when you stop.

Player entities could be handled directly as other entities and this would be resolved (except for own fire overlay, I guess)

Video: https://streamable.com/6w9j50

**Comment by RuffleSteels** [comment]
Yes, this is something I am working on atm so it should be fixed this week!
